# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://www.thefraservalley.ca/events/")
    self.driver.set_window_size(2576, 1416)
    self.driver.execute_script("window.scrollTo(0,194)")
    self.driver.find_element(By.ID, "evc_17105724009659").click()
    self.driver.find_element(By.CSS_SELECTOR, ".evolb_close_btn").click()
    self.driver.find_element(By.ID, "evc_17105724009815").click()
    self.driver.find_element(By.CSS_SELECTOR, ".evolb_close_btn").click()
    self.driver.find_element(By.CSS_SELECTOR, "#evcal_calendar_172 #event_10062_0 .evoet_title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".evolb_close_btn").click()
    self.driver.find_element(By.CSS_SELECTOR, "#evcal_calendar_172 #event_9812_0 .evoet_title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".evolb_close_btn").click()
  
